name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup nuget
      uses: nuget/setup-nuget@v1

    - name: Restore packages
      run: nuget restore ProcessGovernor.sln

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build Release using MSBuild
      run: msbuild ProcessGovernor.sln -m /p:Configuration=Release /p:Platform=x86

    - name: Build Release using MSBuild
      run: msbuild ProcessGovernor.sln -m /p:Configuration=Release /p:Platform=x64

    - name: Rename 64-bit artifacts
      run: |
        Rename-Item -Path "ProcessGovernor\bin\x64\Release\procgov.exe" -NewName "procgov64.exe"
        Rename-Item -Path "ProcessGovernor\bin\x64\Release\procgov.pdb" -NewName "procgov64.pdb"

    - uses: actions/upload-artifact@v2
      with:
        name: procgov
        path: |
          ProcessGovernor\bin\x86\Release\procgov.exe
          ProcessGovernor\bin\x86\Release\procgov.pdb
          ProcessGovernor\bin\x64\Release\procgov64.exe
          ProcessGovernor\bin\x64\Release\procgov64.pdb
